services:
  pipeline-client:
      build:
        context: .
        dockerfile: Dockerfile
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      environment:
        PIPELINE_ID: "${PIPELINE_ID}"
        PIPELINE_SECRET: "${PIPELINE_SECRET}"
        OAUTH_TOKEN: "${OAUTH_TOKEN}"
        DOCKER_USERNAME: "${DOCKER_USERNAME:-}"
        DOCKER_PASSWORD: "${DOCKER_PASSWORD:-}"
        REPO_TOKEN: "${REPO_TOKEN:-}"

        HTTP_URL: "http://host.docker.internal:8080"
        DOCKER_LOGIN: True